version: '3'
services:
  db:
    image: mysql:5.6
    container_name: "mysql_clnd"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_clnd_db
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306

  php:
    build: ./docker/php
    container_name: "php-fpm-clnd"
    volumes:
      - ./src:/var/www

  nginx:
    image: nginx:latest
    container_name: "nginx_clnd"
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php